SELECT_COUNT_QUERY = """
    SELECT COUNT(*) as total FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` {WHERE_CLAUSE}
"""

SELECT_QUERY = """
    SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` {WHERE_CLAUSE} {ORDER_BY_CLAUSE} LIMIT {PER_PAGE} OFFSET {OFFSET}
"""

DISTINCT_MEDICINE_QUERY = """
    SELECT DISTINCT medicine FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
"""

DISTINCT_TYPE_QUERY = """
    SELECT DISTINCT type FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
"""

DISTINCT_ORIGIN_QUERY = """
    SELECT DISTINCT origin FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
"""

DISTINCT_DESTINATION_QUERY = """
    SELECT DISTINCT destination FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
"""
